# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.api_pull_initiate_post_request1 import ApiPullInitiatePostRequest1

class TestApiPullInitiatePostRequest1(unittest.TestCase):
    """ApiPullInitiatePostRequest1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPullInitiatePostRequest1:
        """Test ApiPullInitiatePostRequest1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPullInitiatePostRequest1`
        """
        model = ApiPullInitiatePostRequest1()
        if include_optional:
            return ApiPullInitiatePostRequest1(
                success = True,
                pk = None,
                transfer_id = None,
                session_id = None,
                timestamp = None,
                error_resolve_text = None,
                error_type = internal,
                resolved = None,
                endgrate = endgrate.models.error_list_schema_endgrate.ErrorListSchema_endgrate(
                    provider_info = endgrate.models.configuration_callback_schema_endgrate_provider_info.ConfigurationCallbackSchema_endgrate_provider_info(
                        name = '', 
                        display_name = '', 
                        url = '', 
                        image = '', 
                        auth_type = 'oauth', 
                        specific = endgrate.models.specific.specific(), 
                        endgrate_provider_type = '', ), 
                    integration_info = endgrate.models.error_list_schema_endgrate_integration_info.ErrorListSchema_endgrate_integration_info(
                        name = '', 
                        display_name = '', 
                        method = 'IMPORT', 
                        endgrate_type = '', 
                        supports_associations = True, ), ),
                metadata = {"user_id":1}
            )
        else:
            return ApiPullInitiatePostRequest1(
        )
        """

    def testApiPullInitiatePostRequest1(self):
        """Test ApiPullInitiatePostRequest1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
