# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.configuration_callback_schema_passthrough_schemas_value import ConfigurationCallbackSchemaPassthroughSchemasValue

class TestConfigurationCallbackSchemaPassthroughSchemasValue(unittest.TestCase):
    """ConfigurationCallbackSchemaPassthroughSchemasValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationCallbackSchemaPassthroughSchemasValue:
        """Test ConfigurationCallbackSchemaPassthroughSchemasValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationCallbackSchemaPassthroughSchemasValue`
        """
        model = ConfigurationCallbackSchemaPassthroughSchemasValue()
        if include_optional:
            return ConfigurationCallbackSchemaPassthroughSchemasValue(
                integration_info = endgrate.models.configuration_callback_schema_passthrough_schemas_value_integration_info.ConfigurationCallbackSchema_passthrough_schemas_value_integration_info(
                    name = '', 
                    display_name = '', 
                    method = 'IMPORT', 
                    endgrate_type = '', 
                    supports_associations = True, ),
                var_schema = endgrate.models.configuration_callback_schema_passthrough_schemas_value_schema.ConfigurationCallbackSchema_passthrough_schemas_value_schema(
                    type = 'object', 
                    associations = True, 
                    endgrate_type = '', 
                    properties = endgrate.models.properties.properties(), 
                    title = '', 
                    session_method = '', ),
                passthrough_fields = endgrate.models.configuration_callback_schema_passthrough_schemas_value_passthrough_fields.ConfigurationCallbackSchema_passthrough_schemas_value_passthrough_fields(
                    properties = {customfield1={title=Custom Field 1, type=string}}, 
                    required = [
                        ''
                        ], )
            )
        else:
            return ConfigurationCallbackSchemaPassthroughSchemasValue(
        )
        """

    def testConfigurationCallbackSchemaPassthroughSchemasValue(self):
        """Test ConfigurationCallbackSchemaPassthroughSchemasValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
