# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.pull_initiate_schema import PullInitiateSchema

class TestPullInitiateSchema(unittest.TestCase):
    """PullInitiateSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PullInitiateSchema:
        """Test PullInitiateSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PullInitiateSchema`
        """
        model = PullInitiateSchema()
        if include_optional:
            return PullInitiateSchema(
                completed_webhook = endgrate.models.webhook_schema.WebhookSchema(
                    endpoint = '', 
                    metadata = {user_id=1}, ),
                configuration_webhook = endgrate.models.webhook_schema.WebhookSchema(
                    endpoint = '', 
                    metadata = {user_id=1}, ),
                data_webhook = endgrate.models.data_webhook_schema.DataWebhookSchema(
                    continuous = null, 
                    endpoint = null, 
                    metadata = null, ),
                error_webhook = endgrate.models.webhook_schema.WebhookSchema(
                    endpoint = '', 
                    metadata = {user_id=1}, ),
                field_selection = None,
                passthrough_fields = None,
                passthrough_schemas = None,
                sync = None,
                prepopulate = endgrate.models.properties.properties(),
                provider = None,
                redirect_url = None,
                resource_selection = None,
                save_session = None,
                var_schema = None,
                schema_selection = None,
                statistics = None,
                webhook_concurrency = None,
                bypass_ui = None
            )
        else:
            return PullInitiateSchema(
        )
        """

    def testPullInitiateSchema(self):
        """Test PullInitiateSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
