# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.configuration_callback_schema_schemas_value_integration_info import ConfigurationCallbackSchemaSchemasValueIntegrationInfo

class TestConfigurationCallbackSchemaSchemasValueIntegrationInfo(unittest.TestCase):
    """ConfigurationCallbackSchemaSchemasValueIntegrationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationCallbackSchemaSchemasValueIntegrationInfo:
        """Test ConfigurationCallbackSchemaSchemasValueIntegrationInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationCallbackSchemaSchemasValueIntegrationInfo`
        """
        model = ConfigurationCallbackSchemaSchemasValueIntegrationInfo()
        if include_optional:
            return ConfigurationCallbackSchemaSchemasValueIntegrationInfo(
                name = '',
                display_name = '',
                method = 'IMPORT',
                endgrate_type = '',
                supports_associations = True
            )
        else:
            return ConfigurationCallbackSchemaSchemasValueIntegrationInfo(
        )
        """

    def testConfigurationCallbackSchemaSchemasValueIntegrationInfo(self):
        """Test ConfigurationCallbackSchemaSchemasValueIntegrationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
