# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.completed_callback_schema import CompletedCallbackSchema

class TestCompletedCallbackSchema(unittest.TestCase):
    """CompletedCallbackSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompletedCallbackSchema:
        """Test CompletedCallbackSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompletedCallbackSchema`
        """
        model = CompletedCallbackSchema()
        if include_optional:
            return CompletedCallbackSchema(
                success = True,
                transfer_id = '',
                session_id = '',
                metadata = None,
                endgrate = endgrate.models.completed_callback_schema_endgrate.CompletedCallbackSchema_endgrate(
                    endgrate_type = '', ),
                completed = True
            )
        else:
            return CompletedCallbackSchema(
        )
        """

    def testCompletedCallbackSchema(self):
        """Test CompletedCallbackSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
