# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.transfer_data_schema_inner import TransferDataSchemaInner

class TestTransferDataSchemaInner(unittest.TestCase):
    """TransferDataSchemaInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferDataSchemaInner:
        """Test TransferDataSchemaInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferDataSchemaInner`
        """
        model = TransferDataSchemaInner()
        if include_optional:
            return TransferDataSchemaInner(
                id = '',
                data = {email=susan@youtube.com, first_name=Susan, last_name=Wojicki, full_name=Susan Wojicki, company=YouTube, is_employed=true, age=37, lifecyclestage=lead},
                associations = {
                    'key' : null
                    }
            )
        else:
            return TransferDataSchemaInner(
        )
        """

    def testTransferDataSchemaInner(self):
        """Test TransferDataSchemaInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
