# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.configuration_callback_schema_schemas_value_passthrough_fields_properties_value import ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue

class TestConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue(unittest.TestCase):
    """ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue:
        """Test ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue`
        """
        model = ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue()
        if include_optional:
            return ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue(
                title = '',
                type = ''
            )
        else:
            return ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue(
        )
        """

    def testConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue(self):
        """Test ConfigurationCallbackSchemaSchemasValuePassthroughFieldsPropertiesValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
