# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_completed_webhook_post(self) -> None:
        """Test case for completed_webhook_post

        Completed Webhook
        """
        pass

    def test_configuration_webhook_post(self) -> None:
        """Test case for configuration_webhook_post

        Configuration Webhook
        """
        pass

    def test_data_webhook_post(self) -> None:
        """Test case for data_webhook_post

        Data Webhook
        """
        pass

    def test_error_webhook_post(self) -> None:
        """Test case for error_webhook_post

        Error Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
