# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.endgrate_json_schema import EndgrateJsonSchema

class TestEndgrateJsonSchema(unittest.TestCase):
    """EndgrateJsonSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndgrateJsonSchema:
        """Test EndgrateJsonSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndgrateJsonSchema`
        """
        model = EndgrateJsonSchema()
        if include_optional:
            return EndgrateJsonSchema(
                type = 'object',
                associations = True,
                endgrate_type = 'accounting-address',
                properties = {email={type=string, format=email}, first_name={type=string}, last_name={type=string}, full_name={type=string}, company={type=string}, age={type=number}, is_employed={type=boolean}, lifecyclestage={title=Lifecycle Stage, type=string}},
                required = [
                    ''
                    ],
                title = ''
            )
        else:
            return EndgrateJsonSchema(
        )
        """

    def testEndgrateJsonSchema(self):
        """Test EndgrateJsonSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
