# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.error_list_schema_endgrate_integration_info import ErrorListSchemaEndgrateIntegrationInfo

class TestErrorListSchemaEndgrateIntegrationInfo(unittest.TestCase):
    """ErrorListSchemaEndgrateIntegrationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorListSchemaEndgrateIntegrationInfo:
        """Test ErrorListSchemaEndgrateIntegrationInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorListSchemaEndgrateIntegrationInfo`
        """
        model = ErrorListSchemaEndgrateIntegrationInfo()
        if include_optional:
            return ErrorListSchemaEndgrateIntegrationInfo(
                name = '',
                display_name = '',
                method = 'IMPORT',
                endgrate_type = '',
                supports_associations = True
            )
        else:
            return ErrorListSchemaEndgrateIntegrationInfo(
        )
        """

    def testErrorListSchemaEndgrateIntegrationInfo(self):
        """Test ErrorListSchemaEndgrateIntegrationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
