# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.get_api_statistics200_response import GetApiStatistics200Response

class TestGetApiStatistics200Response(unittest.TestCase):
    """GetApiStatistics200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiStatistics200Response:
        """Test GetApiStatistics200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiStatistics200Response`
        """
        model = GetApiStatistics200Response()
        if include_optional:
            return GetApiStatistics200Response(
                method = 'IMPORT',
                completed = True,
                initiated = '',
                statistics = {"crm-contact":{"batch_size":200,"records":0,"batches":0,"batches_queued":0,"batches_success":2,"batches_fail":0,"records_transferred":2,"completed":true,"provider":"hubspot","integration":"get-contact"}}
            )
        else:
            return GetApiStatistics200Response(
        )
        """

    def testGetApiStatistics200Response(self):
        """Test GetApiStatistics200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
