# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.transfer_response_schema import TransferResponseSchema

class TestTransferResponseSchema(unittest.TestCase):
    """TransferResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferResponseSchema:
        """Test TransferResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferResponseSchema`
        """
        model = TransferResponseSchema()
        if include_optional:
            return TransferResponseSchema(
                success = True,
                transfer_id = '',
                statistics = ''
            )
        else:
            return TransferResponseSchema(
        )
        """

    def testTransferResponseSchema(self):
        """Test TransferResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
