# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from endgrate.models.configuration_callback_schema_passthrough_schemas_value_passthrough_fields import ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields

class TestConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields(unittest.TestCase):
    """ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields:
        """Test ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields`
        """
        model = ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields()
        if include_optional:
            return ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields(
                properties = {customfield1={title=Custom Field 1, type=string}},
                required = [
                    ''
                    ]
            )
        else:
            return ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields(
        )
        """

    def testConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields(self):
        """Test ConfigurationCallbackSchemaPassthroughSchemasValuePassthroughFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
