# coding: utf-8

"""
    Endgrate API

    Endgrate API Reference

    The version of the OpenAPI document: 1.0.0
    Contact: team@endgrate.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data_webhook_schema import DataWebhookSchema
from openapi_client.models.endgrate_json_schema import EndgrateJsonSchema
from openapi_client.models.webhook_schema import WebhookSchema
from typing import Optional, Set
from typing_extensions import Self

class SessionInitiateSchema(BaseModel):
    """
    SessionInitiateSchema
    """ # noqa: E501
    completed_webhook: Optional[WebhookSchema] = Field(default=None, description="Endgrate will POST to this webhook whenever a transfer is completed.")
    configuration_webhook: Optional[WebhookSchema] = Field(default=None, description="Endgrate will POST to this webhook when the session is configured by the user.")
    data_webhook: Optional[DataWebhookSchema] = Field(default=None, description="Endgrate will POST to this webhook whenever new data is received.")
    error_webhook: Optional[WebhookSchema] = Field(default=None, description="Endgrate will POST to this webhook whenever an error occurs.")
    field_selection: Optional[StrictBool] = Field(default=None, description="Whether or not to allow the user to configure field mapping.")
    passthrough_fields: Optional[StrictBool] = Field(default=None, description="Whether or not passthrough fields are allowed.")
    passthrough_schemas: Optional[StrictBool] = Field(default=None, description="Whether or not passthrough schemas are allowed.")
    sync: Optional[StrictBool] = Field(default=None, description="Whether or not to return only updated (new) data when pulling data.")
    prepopulate: Optional[Dict[str, Any]] = None
    provider: Optional[StrictStr] = Field(default=None, description="A pre-selected integration provider. If specified, the user will be directly redirected to the specific authentication page.")
    redirect_url: Optional[StrictStr] = Field(default=None, description="A URL that users will be redirected to after setting up the session..")
    resource_selection: Optional[StrictBool] = Field(default=None, description="Whether or not to allow the user to choose the integrations for a given schema (e.g. choosing \"Get Contacts\" for a contact schema).")
    save_session: Optional[StrictBool] = Field(default=None, description="Whether or not the session should be persisted permanently. If false, sessions will expire after 72 hours.")
    var_schema: Optional[List[EndgrateJsonSchema]] = Field(default=None, description="An array of schemas.", alias="schema")
    schema_selection: Optional[StrictBool] = Field(default=None, description="Whether or not to allow the user to choose which schemas to pull in.")
    statistics: Optional[StrictBool] = Field(default=None, description="Whether or not to allow the user to see transfer statistics.")
    webhook_concurrency: Optional[StrictBool] = Field(default=None, description="Whether or not to execute POST requests to webhooks concurrently.")
    bypass_ui: Optional[StrictBool] = Field(default=None, description="Whether or not the Endgrate UI should be bypassed (Beta).")
    __properties: ClassVar[List[str]] = ["completed_webhook", "configuration_webhook", "data_webhook", "error_webhook", "field_selection", "passthrough_fields", "passthrough_schemas", "sync", "prepopulate", "provider", "redirect_url", "resource_selection", "save_session", "schema", "schema_selection", "statistics", "webhook_concurrency", "bypass_ui"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionInitiateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of completed_webhook
        if self.completed_webhook:
            _dict['completed_webhook'] = self.completed_webhook.to_dict()
        # override the default output from pydantic by calling `to_dict()` of configuration_webhook
        if self.configuration_webhook:
            _dict['configuration_webhook'] = self.configuration_webhook.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_webhook
        if self.data_webhook:
            _dict['data_webhook'] = self.data_webhook.to_dict()
        # override the default output from pydantic by calling `to_dict()` of error_webhook
        if self.error_webhook:
            _dict['error_webhook'] = self.error_webhook.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in var_schema (list)
        _items = []
        if self.var_schema:
            for _item in self.var_schema:
                if _item:
                    _items.append(_item.to_dict())
            _dict['schema'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionInitiateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_webhook": WebhookSchema.from_dict(obj["completed_webhook"]) if obj.get("completed_webhook") is not None else None,
            "configuration_webhook": WebhookSchema.from_dict(obj["configuration_webhook"]) if obj.get("configuration_webhook") is not None else None,
            "data_webhook": DataWebhookSchema.from_dict(obj["data_webhook"]) if obj.get("data_webhook") is not None else None,
            "error_webhook": WebhookSchema.from_dict(obj["error_webhook"]) if obj.get("error_webhook") is not None else None,
            "field_selection": obj.get("field_selection"),
            "passthrough_fields": obj.get("passthrough_fields"),
            "passthrough_schemas": obj.get("passthrough_schemas"),
            "sync": obj.get("sync"),
            "prepopulate": obj.get("prepopulate"),
            "provider": obj.get("provider"),
            "redirect_url": obj.get("redirect_url"),
            "resource_selection": obj.get("resource_selection"),
            "save_session": obj.get("save_session"),
            "schema": [EndgrateJsonSchema.from_dict(_item) for _item in obj["schema"]] if obj.get("schema") is not None else None,
            "schema_selection": obj.get("schema_selection"),
            "statistics": obj.get("statistics"),
            "webhook_concurrency": obj.get("webhook_concurrency"),
            "bypass_ui": obj.get("bypass_ui")
        })
        return _obj


